spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.37:3306/bmanager?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: wjdqhqhdks


  jpa:
          open-in-view: true
          hibernate:
            ddl-auto: create
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: false
          show-sql: true
          properties:
            hibernate.format_sql: true
            dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  mybatis:
    mapper-locations: classpath:mapper/*.xml


  logging:
    level:
      org.hibernate.SQL: debug